### ISSUE TITLE
Moving to this Poste.io version

### ISSUE THREAD

**Issue by kennylajara** [dirtsimple/poste.io#11]
``I have the original Poste.io installed and I am planning to move to this version. 

Do I only have to change the container in the `docker-compose.yml` file? The persisted data and configuration will work the same way?

This is my current `docker-compose.yml` file:
```
# mailserver
version: '3.8'

services:
  mailserver:
    image: analogic/poste.io:latest
    container_name: mailserver
    hostname: mail
    domainname: example.com # Censured for privacy
    restart: always
    ports:
      # Ports 80 and 443 are handled by reverse proxy
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - HTTPS=OFF # HTTPS handled by proxy
      - VIRTUAL_HOST=imap.example.com,mail.example.com,smtp.example.com
      - DISABLE_CLAMAV=TRUE
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "data:/data"
      # Sever-wide sieve filter
      - "/data/custom-sieve/sieve.d:/var/lib/dovecot/sieve.d"
      - "/data/custom-sieve/90-sieve.conf:/etc/dovecot/conf.d/90-sieve.conf"
    networks:
      - "frontend"
      
volumes:
  data:
  
networks:
  frontend:
    external: true
```
