### ISSUE TITLE
different outgoing servers

### ISSUE THREAD

**Issue by rafaello9** [dirtsimple/poste.io#17]
Greetings!

I have not used poste.io before and now I am doing everything for the first time.
Please answer my question.

Here are my configs

/etc/hostname
`mx.mydomain.com`

/etc/hosts
```
127.0.0.1 localhost
178.21.11.32 mx.mydomain.com
193.124.201.33 snd1.mydomain.com
```

#ip a

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:3f:94:66 brd ff:ff:ff:ff:ff:ff
    altname enp0s6
    altname ens6
    inet 178.21.11.32/24 brd 178.21.11.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 193.124.201.33/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe3f:9466/64 scope link
       valid_lft forever preferred_lft forever
```
/root/docker-compose.yml
```
version: "2.3"
services:
  poste:
    image: dirtsimple/poste.io
    restart: always
    network_mode: host
    hostname: mx.mydomain.com
    volumes:
      - /root/poste/:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "LISTEN_ON=178.21.11.32 193.124.201.33"
      - "SEND_ON=178.21.11.32 193.124.201.33"
      - "HTTP_PORT=8080" 
      - "HTTPS_PORT=4433"

```
/root/Data/outbound-hosts.yml
```
default:
  helo: mx.mydomain.com
  ip: 178.21.11.32

snd1.algapro.ru:
  helo: snd1.mydomain.com
  ip: 193.124.201.33

```
If you telnet to snd1.mydomain.com (193.124.201.33), then mx.mydomain.com responds
```
# telnet 193.124.201.33 25
Trying 193.124.201.33...
Connected to 193.124.201.33.
Escape character is '^]'.
220 mx.mydomain.com ESMTP Haraka ready
.....
quit
```
Also, if you send a letter through the snd1.mydomain.com server (193.124.201.33), then you can see in the message headers what mx.mydomain.com receives, and then snd1.mydomain.com
```
Delivered-To: tukxxxx@xxxxx.com
Return-path: <bounce@snd1.mydomain.com>
Authentication-Results: ....... smtp.helo=mx.mydomain.com;
```
My question is this.
If I send via the snd1.mydomain.com server, then how do I get smtp.helo = snd1.mydomain.com in the email headers?
Accordingly, to telnet, so that
```
220 snd1.mydomain.com ESMTP Haraka ready
```
but not so
```
220 mx.mydomain.com ESMTP Haraka ready
```
thanks !!!

**Comment by pjeby** [comment]
So, the HELO setting is for outbound mail only: when you send a message out for the specified domain, it will use the specified IP and it will send a HELO message to the other server with the specified host.  That's all it does.  There is no attempt at masking the identity of the host on incoming connections, as there is only one TLS certificate for incoming connections, so even if you make it a multi-host certificate to cover the other inbound hostnames, you cannot mask the fact that the domains are related on the inbound side.

With regard to the specifics of what you posted, there seem to be some inconsistencies, e.g. snd1.algapro.ru vs snd1.mydomain.com, and I'm uncertain of your MX records or reverse DNS.  (Some systems use reverse DNS in their records, and one reason for allowing HELO customization is to allow matching it to the reverse DNS for the sending IP.)

**Comment by rafaello9** [comment]
>there seem to be some inconsistencies, e.g. snd1.algapro.ru vs snd1.mydomain.com

This is really just a mechanical typo. Of course there will be snd1.mydomain.com
```
default:
  helo: mx.mydomain.com
  ip: 178.21.11.32

snd1.mydomain.com:
  helo: snd1.mydomain.com
  ip: 193.124.201.33
```
I guarantee that all DNS records are correct! Here is the output of the dig commands:
```
#dig -x 193.124.201.33
.........
;; ANSWER SECTION:
33.201.124.193.in-addr.arpa. 86400 IN   PTR     snd1.mydomain.com.

#dig snd1.mydomain.com MX
.........
;; ANSWER SECTION:
snd1.mydomain.com.        86400   IN      MX      10 snd1.mydomain.com.
```
>So, the HELO setting is for outbound mail only: when you send a message out for the specified domain, it will use the specified IP and it will send a HELO message to the other server with the specified host.

But the way you say it does not work for me.
I am using mailwizz script to send messages. In mailwizz, I created a delivery server and specified the connection parameters snd1.mydomain.com there - 193.124.201.33.
And if I send a message through the snd1.mydomain.com server, then the headers in the received message still contain smtp.helo = mx.mydomain.com
```
Delivered-To: tukxxxx@xxxxx.com
Return-path: <bounce@snd1.mydomain.com>
Authentication-Results: ....... smtp.helo=mx.mydomain.com;
```
Please tell me where did I go wrong?
How can I make the helo match the one listed in /root/Data/outbound-hosts.yml for outbound messages?
